on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.BUILD_ENDPOINT }}
          method: 'POST'
          data: ${{ secrets.BUILD_DATA }}
          